export const GET_SIGNUP_SUCCESS = "GET_SIGNUP_SUCCESS";
export const GET_SIGNUP_ERROR = "GET_SIGNUP_ERROR";

export const GET_SIGNIN_SUCCESS = "GET_SIGNIN_SUCCESS";
export const GET_SIGNIN_ERROR = "GET_SIGNIN_ERROR";

export const GET_SIGNIN_ANON_ERROR = "GET_SIGNIN_ANON_ERROR";
export const GET_SIGNIN_ANON_SUCCESS = "GET_SIGNIN_ANON_SUCCESS";

export const GET_SIGNOUT_SUCCESS = "GET_SIGNOUT_SUCCESS";
export const GET_SIGNOUT_ERROR = "GET_SIGNOUT_ERROR";
